### ISSUE TITLE
Your App Still Isn’t Working 

### ISSUE THREAD

**Issue by mrwick16** [shopgoodwill-auction-sniper/shopgoodwill-bid-sniper#22]
I am informing you that the product I paid for is not working and explaining the issues.

The latest message I get tells me that the download is dangerous. And instead of helping and actually fixing the problems you are trying to block me? 

Please issue a full refund immediately if your style is threaten me instead of solving massive issues with the thing you’re trying to sell.

**Comment by shopgoodwill-auction-sniper** [comment]
I understand and we were trying to assist you but you keep complaining about new problems that don't make sense for example you said "Now I can't download the installer it is triggering security warning" but if it worked for you before then it should still work again so don't come here complaining and demanding support, in fact, in order to assist you further you will need to pay for support now $249, and no we don't offer refunds so either pay or get lost and stop wasting our time.

**Comment by shopgoodwill-auction-sniper** [comment]
Hi mrwick16,

We apologize for that encounter you had with the previous customer service rep, we have relieved that customer service rep from their duties. I will be assisting you now, can you please try to installing Bid Sniper again from our Snipeable.com and if you have any further issues please let us know!

Thank you,
Customer Service
