### ISSUE TITLE
Bid Sniper License

### ISSUE THREAD

**Issue by jake35th** [shopgoodwill-auction-sniper/shopgoodwill-bid-sniper#26]
The app was not working.  You suggested I dl the latest version.  Now I am prompted to the pay again, please advise.

**Comment by shopgoodwill-auction-sniper** [comment]
If it's asking you to pay it's because there is no license on your computer, installing or upgrading doesn't delete your license so I am not sure why your license was lost but there is no way for us to activate it you will need to purchase another license...

Also anytime you are experiencing problems simply updating your version and ensuring you have the latest version by running the installation command on our homepage at Snipeable.com solves all problems...

Best regards,
Customer Service

**Comment by jake35th** [comment]
I spend $70.00 on your app.  It never works.  I have sent you screen shots of it not working.  You have told me to down load the latest version, which I did.  Now your telling me I have to pay again?

**Comment by shopgoodwill-auction-sniper** [comment]
No you don't understand we really don't have access to activate the license from here, you will have to purchase it again and the best we can do is give you an immediate refund from here, would you like that?

**Comment by jake35th** [comment]
That happened before and you never refunded me,

**Comment by shopgoodwill-auction-sniper** [comment]
Ok, well that's the best we can do for you but since you don't want it we won't even do that for you bye.
