### ISSUE TITLE
Paid for bid only to have it fail because the software is not time zone aware

### ISSUE THREAD

**Issue by okachobi** [shopgoodwill-auction-sniper/shopgoodwill-bid-sniper#27]
Paid for a bid and then software said "Bid missed" because the site is in PT and my computer is in ET.  The bid was not missed since there is a 3 hour difference. To my surprise, it also consumed the license.

**Comment by shopgoodwill-auction-sniper** [comment]
Hi okachobi,

Can you please tell me if the date times are displayed correctly inside the software when you add your auction item? Unfortunately, there is nothing we can do about the sniped credit that was missed, because we dont have control over the snipes from here, but what we can do is refund you for your missed credit and also give you 1 month unlimited for free so I would suggest is to buy the 1 month unlimited package for $9.99 that way you can ensure you have enough credits to troubleshoot the issue, and then we will refund your purchase and continue to help you with the time zone issue...

**Comment by shopgoodwill-auction-sniper** [comment]
actually we have found the issue and are releasing a fix for it now, it should be ready in the next few hours, we will notify you here when it is ready...

**Comment by shopgoodwill-auction-sniper** [comment]
Hi okachobi,

Thank you for your patience while we fixed the issue, we have released an update version 24.08.02.2059 now which can be updated/installed by running the installation command on our homepage again at Snipeable.com

Please let us know if we can be of further assistance!

Best regards,
Customer Service

**Comment by shopgoodwill-auction-sniper** [comment]
Hi okachobi,

We have released the new ShopGoodwill Auction Sniper version 24.09.04.1440 for Windows and version 24.09.04.1515 for Mac which resolves the issue you were experiencing!

We have also added the new "Auto Max Bid" feature which basically determines the maximum bid for you at the last second of a ShopGoodwill auction ensuring you win every ShopGoodwill auction you snipe at the last second of an auction using Bid Sniper!

You can update to the newest version by following the install/update instructions on our homepage at http://Snipeable.com

Please let us know if you need any further assistance...

Best regards,
Customer Service
Snipeable.com
